# Generated by Django 3.1 on 2020-10-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_con',
        ),
        migrations.DeleteModel(
            name='tbl_log',
        ),
    ]
