# Generated by Django 3.1 on 2020-10-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0004_tbl_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cont',
            name='msg',
            field=models.CharField(max_length=1000),
        ),
    ]
