# Generated by Django 3.1 on 2020-11-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0005_auto_20201014_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_log',
            name='reply',
            field=models.CharField(default='Reply', max_length=1000),
        ),
        migrations.AddField(
            model_name='tbl_log',
            name='replymessage',
            field=models.CharField(default='-----', max_length=1000),
        ),
    ]
