# Generated by Django 3.1 on 2020-11-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0006_auto_20201103_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_log',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='tbl_log',
            name='replymessage',
        ),
        migrations.AddField(
            model_name='tbl_cont',
            name='reply',
            field=models.CharField(default='Reply', max_length=1000),
        ),
        migrations.AddField(
            model_name='tbl_cont',
            name='replymessage',
            field=models.CharField(default='-----', max_length=1000),
        ),
    ]
