# Generated by Django 3.1 on 2020-11-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0007_auto_20201104_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='file')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
            ],
        ),
    ]
